# Generated by Django 4.1 on 2023-05-13 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_rename_variation_cartitems_color_cartitems_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.color'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.productsize'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='919ebe8c', max_length=10, unique=True),
        ),
    ]
